### ISSUE TITLE
Fix mappings for answer choices on multiple choice questions in PHQ9 form

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#10]
## Describe the bug
The mappings for 2 multiple choice questions on the PHQ9 form are not matching with the answer choices in Salesforce. The transformations required are in the mapping [sheet](https://docs.google.com/spreadsheets/d/1CXrMYL0hELSeRkjJLUROTR0A3udJ0Yq8PQZhUtTQokk/edit#gid=225222898). The two questions are:
`/begin_interview/position_of_respondent_in_the_household`
`/begin_interview/what_is_your_marital_status`

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/pd3yk4/runs/rj5zd88j

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertPHQ9.js

### state.json
https://www.openfn.org/projects/pd3yk4/messages?endDate=2021-05-12T11%3A24%3A11.741Z&triggerId=ty8dr8

## Expected behavior
`INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST`error message is not showing. 

## To test/resolve
[Rerun](https://www.openfn.org/projects/pd3yk4/runs/rj5zd88j) the job and make sure that error message is no longer showing. FYI there may be another error message that shows after but this issue can be closed after this specific error is resolved.

**Comment by chaiwa-berian** [comment]
@aleksa-krolls and @daissatou2 , this is fixed. See the run [here](https://www.openfn.org/projects/pd3yk4/runs/rwaew43z). Thanks.
