### ISSUE TITLE
Calculate Age from DOB for PHQ9 form

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#13]
## Background, context, and business value

Calculate age using `form.hidden_properties.date_of_birth` and today's date and store in `Age_of_Participant__c` in Salesforce.

## state.json
https://www.openfn.org/projects/pd3yk4/messages/mwbaa8a5

## output.json
1. Rerun this https://www.openfn.org/projects/pd3yk4/runs/rx858zky
2. Confirm correct age is being mapped to `Age_of_Participant__c`

**Comment by chaiwa-berian** [comment]
@aleksa-krolls This is fixed. See run [here](https://www.openfn.org/projects/pd3yk4/runs/ryak5njd).

**Comment by aleksa-krolls** [comment]
@daissatou2 if this is all resolved, can you please close the issue? (Keep open if you're anticipating any further feedback.)
