### ISSUE TITLE
Missing mappings in Register Participant job - return whichever value is present

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#14]
## Describe the bug
There are two versions of the `Register Participant` form. The `Upsert Register Participant` job should be able to handle both versions of the form. I.e the job should recognize both paths for one particular field. 

Ex. `form.question1.participant_first_name` & `form.new_participants.participant_first_name` should both map to `First_Name__c`.

Currently, the Skillz Plus Club version isn't working. In the mapping [sheet](https://docs.google.com/spreadsheets/d/1CXrMYL0hELSeRkjJLUROTR0A3udJ0Yq8PQZhUtTQokk/edit#gid=914514692), this version is noted at the bottom. 

### expression.js
https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/2.d.upsertRegisterParticipant.js

### state.json

Skillz plus club version (currently failing): https://www.openfn.org/projects/pd3yk4/messages/m6645zqa
General version (currently passing): https://www.openfn.org/projects/pd3yk4/runs/r6gedrxw

## Expected behavior
When a user submits either the `Skillz Plus Club Register Participants` form or the `General Register Participant` form, the `Upsert Register Participant` job should be able to successfully sync. 

## To test/resolve
1. Please test the change on OpenFn.org by re-running this [run](https://www.openfn.org/projects/pd3yk4/runs/rwapee6p) and confirming success.

**Comment by taylordowns2000** [comment]
While moving `new_participants` into a `question1` array definitely sounds like it needed to be done*, it doesn't resolve the `Cannot read property '@case_id' of undefined` error. I'll take a look at that next.

* @daissatou2 , have I interpreted this correctly?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 the case_id path is `new_participants[*].create_skillz_plus_participant.case.@case_id` so looks like just need to add `create_skillz_plus_participant` to the path? Or is it more complicated b/c the operation is within the `each(...)`? 
![image](https://user-images.githubusercontent.com/16758106/119316488-adf03080-bc7f-11eb-8c42-4fa4a14c2e91.png)

**Comment by taylordowns2000** [comment]
This is a separate issue but was resolved over here: https://github.com/OpenFn/grassroot-soccer/issues/15

Thank you for the mapping!

**Comment by aleksa-krolls** [comment]
@daissatou2 @taylordowns2000 can we close this issue?
