### ISSUE TITLE
Attendance 2 Job Error

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#25]
## Describe the bug
`Attendance` and `Attendance 2` are identical jobs that just have different triggers.

Why is [`Attendance`](https://www.openfn.org/projects/pd3yk4/jobs/jyjxnx) passing and [`Attendance 2`](https://www.openfn.org/projects/pd3yk4/jobs/jvrqxp) failing for the same [message](https://www.openfn.org/projects/pd3yk4/messages/mgkb54wq)? Please take a look at the associated runs for this message. 

This is another [message](https://www.openfn.org/projects/pd3yk4/messages/m3p78rbd) for which both jobs passed.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/pd3yk4/runs/r3xj9r94

### expression.js
Link to the job itself: https://www.openfn.org/projects/pd3yk4/jobs/jvrqxp

### state.json
https://www.openfn.org/projects/pd3yk4/messages/mgkb54wq

## Expected behavior
Since the two jobs are identical, both should pass or fail against the same message.

## To test/resolve
`. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/pd3yk4/runs/r3xj9r94) and confirming success.

**Comment by aleksa-krolls** [comment]
@daissatou2 Looks like this Attendance 2 job was on the `latest` Salesforce adaptor version and not version `v2.0.0`. I updated the job and was able to successfully re-run: https://www.openfn.org/projects/pd3yk4/runs/rg5r3zpa
Can you please check out the output? If it looks good, go ahead and re-run these Attendance 2 runs. 

@lakhassane can you remind us why we're on this specific Salesforce adaptor version? Should we add to our documentation that ALL of these GRS Salesforce jobs should be on this version?

**Comment by lakhassane** [comment]
@aleksa-krolls it's because it's not release on prod yet. We were waiting to test and see if there is no update needed on salesforce.

I will release that version for Taylor so `latest`will work, but it's preferable if those jobs are locked on `v2.0.0`

**Comment by aleksa-krolls** [comment]
@lakhassane no rush to release, just good to know for us. @taylordowns2000 please make sure all client Salesforce jobs are version-locked before we do any big release.
