### ISSUE TITLE
TypeError on Upsert Pre Challenges Job Run

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#29]
## Describe the bug
We are seeing this error for the `Upsert Pre Challenges` job: 
`TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters`

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/pd3yk4/runs/rzdgeadm

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertPreChallenges.js

### state.json
https://www.openfn.org/projects/pd3yk4/messages/mrb5zn98

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (link) and confirming success.]

**Comment by aleksa-krolls** [comment]
@daissatou2 Looks like Mamadou has resolved. Please re-process any failures and continue to let Mamadou know if any other issues pop up or help needed on GRS... you can add any new issues to the bottom of the backlog.
