### ISSUE TITLE
GRS CommCare to Salesforce sync more forms 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#3]
## Background, context, and business value

See original issue #1.

## The specific request, in as few words as possible
[See here](https://docs.google.com/spreadsheets/d/1CXrMYL0hELSeRkjJLUROTR0A3udJ0Yq8PQZhUtTQokk/edit#gid=0) for the mapping sheet. 

Create the following jobs that execute the following steps:
_Extract forms from CommCare_

1. GET the following form data from CommCare:
`Home Visit Log Form`
`Coach Session Register`
`Attendance`
`HIV Testing Event Snapshot`
`Malaria Testing Event Snapshot`
`PHQ9`
`Malaria Testing Event Statistics`
`HIV Testing Event Statistics`
See CommCare API docs and this example GET job that contains the xmnls ids: https://www.openfn.org/projects/pd3yk4/jobs/jvebnp
We want to extend this job to send 1 GET request for every form.
Also, if you add this job to Github, can you please remove the Inbox URL from the expression?

Map CommCare forms to Salesforce
2. Upsert `Home Visit Log Form` in Salesforce. This job should upsert `Home Visit` records using `id` as the unique identifier.  
3. Upsert `Coach Session Register` in Salesforce. This form records the attendance of coaches in Intervention sessions. The job should upsert the attendance object using `Intervention Name` and ... as the unique identifier.
5. Upsert `Attendance` in Salesforce. This form records the attendance of coaches in Intervention sessions. The job should upsert the attendance object using `Intervention Name` and `Participant Name` as the unique identifier.
6. Upsert `HIV Testing Event Snapshot` in Salesforce. This job should upsert `Event` records using 'Name' as the unique identifier. 
7. Upsert `Malaria Testing Event Snapshot` in Salesforce. This job should upsert `Event` records using 'Name' as the unique identifier.
8. Upsert `PHQ9` in Salesforce. This job should upsert `New PHQ 9 Strong Minds` records using `id` as the unique identifier.
9.  Upsert `Malaria Testing Event Statistics` in Salesforce. This job should upsert `Event` records using `Name` as the unique identifier.
10.  Upsert `HIV Testing Event Statistics` in Salesforce. This job should upsert `Event` records using `Name` as the unique identifier.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 we have a load of GRS jobs that need work. Preferably Mamadou can focus on the more complex Primero, WCS, and MF issues over the next couple days where he has lots of context. Is there any other engineer who can jump on this today/ next week? This is the bottleneck I was anticipating...

**Comment by taylordowns2000** [comment]
Absolutely. @chaiwa-berian or I can look at this (and the other) as soon as we submit on DS!

**Comment by aleksa-krolls** [comment]
@daissatou2 looks like the new salesforce release is done: https://openfn.slack.com/archives/G2LJCFFDW/p1620280297071000

@taylordowns2000 confirming we're good to test now?
