### ISSUE TITLE
ReferenceError [Error]: sc is not defined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/grassroot-soccer#32]
## Describe the bug
See run failure: https://www.openfn.org/projects/pd3yk4/runs/06167f34-5790-7d69-bc23-26406c14cb48

## To Reproduce
Feel free to re-run on prod. 

### expression.js
https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/2.d.upsertRegisterParticipant.js

### state.json
See `GRS Salesforce Prod`
https://www.openfn.org/projects/pd3yk4/messages/061445aa-c000-7678-99db-28f58b6c3b20

**Comment by daissatou2** [comment]
Hey @elias-ba we are seeing the same emoji error now: https://www.openfn.org/projects/pd3yk4/runs/06168202-196a-70dc-ac2a-7891ce7d7556

**Comment by aleksa-krolls** [comment]
@elias-ba We will pick this up again on Monday, but can you please leave a status update here on GH regarding where you left off yesterday?
(Want to make sure there's not a quick here by switching the adaptor versions from `v2.7.1` to something else
 cc @taylordowns2000)

**Comment by taylordowns2000** [comment]
This `sc` typo was was introduced and fixed yesterday. Closing and moving recent comments to the correct issue.
