### ISSUE TITLE
Attendance Non Skillz failing for some messages

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#34]
## Describe the bug
The `Attendance Non Skillz` job is failing for certain messages because of the `replace` function. 
This is a message that failed: https://www.openfn.org/projects/pd3yk4/messages/0614381b-b000-7ddc-aa95-1af58212b0e2
A message that passed: https://www.openfn.org/projects/pd3yk4/messages/0617805a-e87f-741e-9e39-fde5086b0d71

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/pd3yk4/runs/06177568-c451-7e99-a837-c0e537019563

### expression.js
Link to the job itself in Github: https://www.openfn.org/projects/pd3yk4/jobs/jvrqxp

### state.json
LP: GRS Salesforce Production 
https://www.openfn.org/projects/pd3yk4/messages/0614381b-b000-7ddc-aa95-1af58212b0e2

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/pd3yk4/runs/06177568-c451-7e99-a837-c0e537019563) and confirming success.]

**Comment by aleksa-krolls** [comment]
@daissatou2 Because this data is for a bad form version, can we close this issue? Any other GRS issues we should take a look at?
