### ISSUE TITLE
`upsertRiskVulnerabilityNewReferrals` job not properly upserting Risk Assessment objects

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#36]
## Describe the bug
As discussed on the call, we made this [change](https://github.com/OpenFn/grassroot-soccer/commit/cd886d78dee4742bd74accf80809ec60a86cfb27) in the `upsertRiskVulnerabilityNewReferrals` job because I noticed that we are not upserting `Risk Assessments` even when they are present in the message. See this [run](https://www.openfn.org/projects/grs-integrations/runs/062041d9-d3c1-7d72-b819-12315bb00c09) and [message](https://www.openfn.org/projects/grs-integrations/messages/061770a2-b9a9-70a8-8ff1-b1f0806a8609) for example. 

But after making that change, we are now seeing this JSON parser error: https://www.openfn.org/projects/grs-integrations/runs/062062fd-35e8-732b-b080-f7b4562a8871

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/grs-integrations/runs/062062fd-35e8-732b-b080-f7b4562a8871

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertRiskVulnerabilityNewReferrals.js

### state.json
https://www.openfn.org/projects/grs-integrations/messages/061770a2-b9a9-70a8-8ff1-b1f0806a8609

{
  "configuration": "GRS Salesforce Production",
  "data": "Data linked above"
}

## Expected behavior
The example message here should upsert both `Risk Assessment` and `Newreferral` objects, not just one. 

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run ([link](https://www.openfn.org/projects/grs-integrations/runs/062062fd-35e8-732b-b080-f7b4562a8871)) and confirming success.]

**Comment by lakhassane** [comment]
@daissatou2 can you link LP credentials to be able to test?
