### ISSUE TITLE
Add new mapping to upsertRiskVulnerabilityNewReferrals job 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#37]
## Background and specific request
As discussed, insert new mapping in the [upsertRiskVulnerabilityNewReferrals](https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertRiskVulnerabilityNewReferrals.js) job. 

Commcare source value: `state.data.form.client_information.intervention_name`
SF Destination field: `Event__c` on the `Newreferrals__c` object 

This field should be configured as a relationship where the lookup field is the `CommCare_Case_ID__c`. 

**Transformation**: There are two versions of this form. One that has `state.data.form.client_information.intervention_name` in [state](https://www.openfn.org/projects/grs-integrations/messages/061770a2-b9a9-70a8-8ff1-b1f0806a8609) and [one](https://www.openfn.org/projects/grs-integrations/messages/06205ac9-9193-767f-b5b4-5970d388c884) that doesn't. The job should be able to handle both. If the `intervention_name` is missing from state, the job should  not upsert this field.

I have added all of this information to the [mappings](https://docs.google.com/spreadsheets/d/1CXrMYL0hELSeRkjJLUROTR0A3udJ0Yq8PQZhUtTQokk/edit#gid=1668919710&range=58:58).

## state.json
{
"configuration": "GRS Salesforce Production",
"data": "Data linked above"
}

## expression.js
[upsertRiskVulnerabilityNewReferrals](https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertRiskVulnerabilityNewReferrals.js)

## output.json

Running against this [state](https://www.openfn.org/projects/grs-integrations/messages/06205ac9-9193-767f-b5b4-5970d388c884) should result in a successful run where `Event__c` is not inserted.
Running against this [state](https://www.openfn.org/projects/grs-integrations/messages/061770a2-b9a9-70a8-8ff1-b1f0806a8609) should result in a successful run where `Event__c` is inserted.

**Comment by lakhassane** [comment]
@daissatou2 corrections done here:

For when there is no `intervention_name`: https://www.openfn.org/projects/grs-integrations/runs/0620a337-d12c-7429-92ba-47c4f9279f6e

For when there is `intervention_name`: https://www.openfn.org/projects/grs-integrations/runs/0620a33a-3e7b-74e2-bea4-778b9c463777
For that one there is an error you need to check because the intervention_name value does not exist in salesforce
