### ISSUE TITLE
Do not fail jobs if related Participant record not found

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#38]
## Background, context, and business value
The GRS team wants us to ignore certain `Register Participant` forms which are submitted. This is causing other forms which might reference the participant we didn't sync to fail. Let's update the appropriate jobs to not fail these runs but instead log a helpful message.

## The specific request, in as few words as possible

At the beginning of each of the jobs below: check if the related `Person__c` record exists in Salesforce. 
```
SELECT Participant_Identification_Number_PID__c from Person__c where Participant_Identification_Number_PID__c  = {INSERT ID HERE}
```

Below, I have included the paths for the source field for the `Participant_Identification_Number_PID__c` to search for the record in SF. 
1. If the Person exists, the job should continue as usual. 
2. If the Person doesn't exist in Salesforce, stop the job and log the message `"Participant not found with Participant_Identification_Number_PID__c: [INSERT ID HERE]"`. This run should still show as successful, but this message should be logged. 

I have listed the paths & sample runs for the `Participant_Identification_Number_PID__c` for each job below. Once you finish, you can rerun each of those messages to ensure they no longer fail. 

1. [upsertAttendanceSkillsPlusClub](https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertAttendanceSkillsPlusClub.js) - `form.attendance_list.update_participant_cases.item[].@id`- [failed run](https://www.openfn.org/projects/grs-integrations/runs/06213b72-1d5d-72ce-8bf6-7ceda9450f28)
2. [upsertHomeVisitLog](https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertHomeVisitLog.js) - `${form.case['@case_id']}` - [failed run](https://www.openfn.org/projects/grs-integrations/runs/06213b84-c1d3-79a9-a350-7a60f4456a73)
3. [upsertPostChallenges](https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertPostChallenges.js) - `form.case.@case_id` - [failed run](https://www.openfn.org/projects/grs-integrations/runs/0620e4a3-e105-79cc-9b3e-4a1b15676265)
4. [upsertPreChallenges](https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertPreChallenges.js) - `form.case.@case_id` - [failed run](https://www.openfn.org/projects/grs-integrations/runs/0620e292-4981-7330-a965-e01b66c43764)

For example, instead of this [run](https://www.openfn.org/projects/grs-integrations/runs/0620e4a3-e105-79cc-9b3e-4a1b15676265) failing it should pass and log the message " Participant not found with Participant_Identification_Number_PID__c: [INSERT ID HERE]". 
Since this is a `upsertPostChallenges` run, use the value in `form.case.@case_id` from the message to search in SF if a `Person__c` record has `Participant_Identification_Number_PID__c` equal to that value. 

## state.json

{
"configuration": "GRS Salesforce Production",
"data": "Run links with messages linked above"
}

## expression.js
Jobs linked above

**Comment by aleksa-krolls** [comment]
@daissatou2 fyi, I saw you created this and went ahead and added the Salesforce SOQL query to your request description above. Once you're done drafting this issue, please assign to @lakhassane and @grayey and move to Backlog.

**Comment by aleksa-krolls** [comment]
@grayey @lakhassane can you two work on this today? Let @daissatou2 know if any questions.

**Comment by grayey** [comment]
I will arrange with @lakhassane, see if we can today.

**Comment by lakhassane** [comment]
@daissatou2 we made corrections. For job 2, 3 and 4. Find the succesfull runs here.

`upsertHomeVisitLog.js` => https://www.openfn.org/projects/grs-integrations/runs/062150b0-bbdb-78df-999c-a6c89bb48c8e
`upsertPostChallenges.js` => https://www.openfn.org/projects/grs-integrations/runs/062150a0-0478-7725-bdaa-5f186aee746e
`upsertPreChallenges.js` => https://www.openfn.org/projects/grs-integrations/runs/062150be-5910-702a-8f5b-df4280e2f858

**Comment by daissatou2** [comment]
@lakhassane for `upsertAttendanceSkillsPlusClub` please use the first item in the array

**Comment by daissatou2** [comment]
@lakhassane @grayey moving this back to backlog, please do the same for the new job below: 

[upsertAttendanceNonSkillz](https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertAttendanceNonSkillz) - `form.attendance_list.update_participant_cases.item[].@id` - [failed run](https://www.openfn.org/projects/grs-integrations/runs/06214f1b-e35c-7848-b241-8af9f0c82266). Please check the first item in the array.

**Comment by grayey** [comment]
@daissatou2 this is done. [Here's a successful run](https://www.openfn.org/projects/grs-integrations/runs/062160e2-d3bf-74de-a948-dbc4aa959eed).
