### ISSUE TITLE
Update the `Attendance Non Skillz` job to NOT sync any data if no participant attendance data is provided

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/grassroot-soccer#40]
## Background, context, and business value
We have been seeing `Attendance Non Skillz` messages in the OpenFn inbox that do not have any participant data. These are currently causing the [job](https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertAttendanceNonSkillz.js) to [fail](https://www.openfn.org/projects/grs-integrations/runs/0632996f-00ee-7c52-a056-05456630ae8d). 

## The specific request, in as few words as possible

Update the `Attendance Non Skillz` job to NOT sync any data if no participant attendance data is provided in the message. If `state.data.form.attendance_list.update_participant_cases.item[]` is missing from the message, instead of attempting to sync data to Salesforce, the job should end(pass) and log the message "No participant attendance data was provided".  

## state.json

```json
{
  "configuration": ["SEE LAST PASS: 'GRS Salesforce Sandbox'"],
  "data": https://www.openfn.org/projects/grs-integrations/messages/0632996e-f7c3-7e69-9c3b-3b44c69a1f96
}
```

## adaptor
language-salesforce

## trigger
`Attendance Generic (Both Skillz & Non Skillz)` trigger on platform

## expression.js
https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/upsertAttendanceNonSkillz.js

**Comment by ritazagoni** [comment]
hey @daissatou2 this is ready to test
