### ISSUE TITLE
Update Attendance job to upsert 1 Attendance for each item in array

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/grassroot-soccer#9]
## Background, context, and business value
This is similar to changes made for issue #5 . 

## The specific request, in as few words as possible
For every 1 `item:[...]` in state, upsert `Attendance__c`. 

## state.json
https://www.openfn.org/projects/pd3yk4/messages/mn575657

## expression.js
https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/2.d.upsertRegisterParticipant.js

## output.json
Please re-run this on prod to test: https://www.openfn.org/projects/pd3yk4/messages/m6646qp5

**Comment by chaiwa-berian** [comment]
@aleksa-krolls , @daissatou2  and I worked on this, and it works. Pushing it to review. Thanks.
